;------------------------------------------------------------------------------
; Gabriel benchmarks
(define boyer-iters        50)
(define browse-iters      600)
(define cpstak-iters     5000)
(define ctak-iters        100)
(define dderiv-iters  4000000)
(define deriv-iters   4000000)
(define destruc-iters    1000)
(define diviter-iters 4000000)
(define divrec-iters  1000000)
(define puzzle-iters      400)
(define tak-iters        5000)
(define takl-iters       1000)
(define trav1-iters       500)
(define trav2-iters       150)
(define triangl-iters      50)

; Kernighan and Van Wyk benchmarks
(define ack-iters          40)
(define array1-iters       10)
(define cat-iters           1)
(define string-iters      150)
(define sum1-iters          3)
(define sumloop-iters      40)
(define tail-iters          3)
(define wc-iters            3)

; C benchmarks
(define fft-iters       50000)
(define fib-iters           5)
(define fibfp-iters         8)
(define mbrot-iters      1000)
(define nucleic-iters       4)
(define pnpoly-iters  1000000)
(define sum-iters      300000)
(define sumfp-iters    100000)
(define tfib-iters         20)

; Other benchmarks
(define conform-iters      40)
(define dynamic-iters      20)
(define earley-iters      200)
(define fibc-iters      15000)
(define graphs-iters      300)
(define lattice-iters       1)
(define matrix-iters      400)
(define maze-iters       4000)
(define mazefun-iters    1000)
(define nqueens-iters    2000)
(define paraffins-iters  1000)
(define peval-iters       200)
(define pi-iters           20)
(define primes-iters   200000)
(define ray-iters           5)
(define scheme-iters    20000)
(define simplex-iters  500000)
(define slatex-iters       20)
(define perm9-iters        20)
(define nboyer-iters      100)
(define sboyer-iters      100)
(define gcbench-iters       1)
(define compiler-iters    300)

; New benchmarks
(define parsing-iters    1000)
(define gcold-iters     10000)
(define quicksort-iters    10) ; uses bignums in rand, must fix
(define nbody-iters         1) ; nondeterministic (order of evaluation)